# Google Colab. Introduction

## Markdown



Markdown | Preview
--- | ---
`**bold text**` | **negritas**
`*italicized text*` or `_italicized text_` | *italicas*
`` `Monospace` `` | `Monospace`
`~~strikethrough~~` | ~~strikethrough~~
`[A link](https://www.google.com)` | [A link](https://www.google.com)
`![An image](https://www.google.com/images/rss.png)` | ![An image](https://www.google.com/images/rss.png)


---
Headings are rendered as titles.

```markdown
# Section 1
# Section 2
## Sub-section under Section 2
### Sub-section under the sub-section under Section 2
# Section 3
```

# Section 1
# Section 2
## Sub-section under Section 2
### Sub-section under the sub-section under Section 2
# Section 3

The table of contents, available on the left side of Colab, is populated using at most one section title from each text cell.

---

```markdown
>One level of indentation
```

>One level of indentation


```markdown
>>Two levels of indentation
```

>>Two levels of indentation

---

Code blocks

````
```python
print("a")
```
````

```python
print("a")
```

---

Ordered lists:
```markdown
1. One
1. Two
1. Three
```
1. One
1. Two
1. Three

---

Unordered lists:
```markdown
* One
* Two
* Three
```
* One
* Two
* Three

---

Equations:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$


 ---

Tables:
```markdown
First column name  | Second column name 
-------------------|------------------
Row 1, Col 1       | Row 1, Col 2 
Row 2, Col 1       | Row 2, Col 2 

```

First column name  | Second column name 
-------------------|------------------
Row 1, Col 1       | Row 1, Col 2 
Row 2, Col 1       | Row 2, Col 2 

---

Horizontal rules:
```markdown
---
```

---



## Code

You can run this types of code in Google Colab <br>
Bash<br>
HTML <br>
Python<br>

### Bash

Bash is a command-line interface based on UNIX. You can use the following commands:

In [ ]:
!ls /bin

bash	       false	   more			 systemd-machine-id-setup
bunzip2        fgrep	   mount		 systemd-notify
bzcat	       findmnt	   mountpoint		 systemd-sysusers
bzcmp	       fuser	   mv			 systemd-tmpfiles
bzdiff	       fusermount  networkctl		 systemd-tty-ask-password-agent
bzegrep        grep	   nisdomainname	 tar
bzexe	       gunzip	   pidof		 tempfile
bzfgrep        gzexe	   ps			 touch
bzgrep	       gzip	   pwd			 true
bzip2	       hostname    rbash		 udevadm
bzip2recover   ip	   readlink		 ulockmgr_server
bzless	       journalctl  rm			 umount
bzmore	       kill	   rmdir		 uname
cat	       kmod	   run-parts		 uncompress
chgrp	       less	   sed			 vdir
chmod	       lessecho    sh			 wdctl
chown	       lessfile    sh.distrib		 which
cp	       lesskey	   sleep		 ypdomainname
dash	       lesspipe    ss			 zcat
date	       ln	   stty			 zcmp
dd	       login	   su			 zdiff
df	       loginctl    sync			 zegrep
dir	       ls	   systemctl		 zfgrep
dmesg	       lsblk	   systemd		 zforce
dnsdoma

In [ ]:
!echo 'HELLO'

HELLO


### HTML

In [ ]:
%%html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 450 400" width="200" height="200">
  <rect x="80" y="60" width="250" height="250" rx="20" style="fill:red; stroke:black; fill-opacity:0.7" />
  <rect x="180" y="110" width="250" height="250" rx="40" style="fill:blue; stroke:black; fill-opacity:0.5;" />
</svg>

### Python

In [ ]:
print('Hello')

Hello


## Google Drive

You can connecto Google Drive tools into Google Colab

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!ls drive/MyDrive/

'AURA_RAW___2022-10-24___20;30;43.csv'	    Ideas
'AURA_RAW___2022-10-24___20;30;43.gsheet'  'Jira Stuff.gdraw'
'BD and simulator.gsheet'		   'Modelo de Toxicometro.gdraw'
'Colab Notebooks'			   'NFT Aura Design.gdraw'
 Colorin.gdraw				   'pagina finsulate.pdf'
'Dibujo sin título.gdraw'		   'Pensamientos 22 12 22.gdoc'
'El día que me crypto estafaron.gslides'   'Problema de Esfuerzo.gsheet'
 EMFUTECH				    Proyecto.gdraw
'hyc-bxnt-aak - 17 dic 2021 (1).gjam'	   'Proyecto Personal.gslides'
'hyc-bxnt-aak - 17 dic 2021 (2).gjam'	   'React build'
'hyc-bxnt-aak - 17 dic 2021 (3).gjam'	    Roadmap
'hyc-bxnt-aak - 17 dic 2021 (4).gjam'	   'Sentiment Detection.gform'
'hyc-bxnt-aak - 17 dic 2021 (5).gjam'	   'Story Telling.gdoc'
'hyc-bxnt-aak - 17 dic 2021 (6).gjam'	   'System idea .gdraw'
'hyc-bxnt-aak - 17 dic 2021 (7).gjam'	   'Time Series.gslides'
'hyc-bxnt-aak - 17 dic 2021.gjam'


In [ ]:
!touch drive/MyDrive/hola.txt

In [ ]:
!echo 'hello' >>  drive/MyDrive/hola.txt

In [ ]:
!cat  drive/MyDrive/hola.txt

hello


### Using Python

In [ ]:
1,2,3,4
'cadena de texto'
1.2

1.2

In [ ]:
#comentario

In [ ]:
type(1.2)

float

In [ ]:
tupla = (1,2)

In [ ]:
arreglo = ['uno', 'dos']
diccionario = {'uno':'valor', 'dos': 'valor'}

In [ ]:
print( arreglo[0] )
print( arreglo[1] )

In [ ]:
diccionario['tres'] = arreglo

In [ ]:
diccionario

{'uno': 'valor', 'dos': 'valor', 'tres': ['uno', 'dos']}

In [ ]:
print('este es un texto')

este es un texto


In [ ]:
x = 'mi variable'
print(f'esto imprime variableS: {x}')

esto imprime variableS: mi variable


## Loops and cycles

Use import to import libraries <br>
You can also name the library as a variable using the keyword "as" <br>

In [ ]:
import numpy as np

dir allows us to see what is inside the library

In [ ]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [ ]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

## Libraries to work with Machine Learning

In [ ]:
import numpy as np # Vectores
import pandas as pd # Tablas 
import sklearn # Machine Learning
import tensorflow as tf # Deep Learning

### numpy

Works with vectors

In [ ]:
n = np.arange(1,3)
m = np.arange(1,3)

In [ ]:
print(n, m)

[1 2] [1 2]


In [ ]:
np.dot(n, m)

5

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.linspace(0,100, 5)

array([  0.,  25.,  50.,  75., 100.])

### pandas
Creates data tables refered as dataframes

In [ ]:
df = pd.DataFrame(n,m)
df

0
1  1
2  2

In [ ]:
df.reset_index(inplace=True)
df

index  0
0      1  1
1      2  2

In [ ]:
df.columns = ['fist','second']
df

fist  second
0     1       1
1     2       2

In [ ]:
df['fist'] = [3,4]
df

fist  second
0     3       1
1     4       2

In [ ]:
df.set_index('second')

fist
second      
1          3
2          4

In [ ]:
df['second'] = df['second'].apply(lambda x: f'hola {x}')
df

fist  second
0     3  hola 1
1     4  hola 2

In [ ]:
!pip freeze

absl-py==1.4.0
alabaster==0.7.13
albumentations==1.2.1
altair==4.2.2
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arviz==0.15.1
astropy==5.2.2
astunparse==1.6.3
attrs==23.1.0
audioread==3.0.0
autograd==1.5
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
blis==0.7.9
blosc2==2.0.0
bokeh==2.4.3
branca==0.6.0
CacheControl==0.12.11
cached-property==1.5.2
cachetools==5.3.0
catalogue==2.0.8
certifi==2022.12.7
cffi==1.15.1
chardet==4.0.0
charset-normalizer==2.0.12
chex==0.1.7
click==8.1.3
cloudpickle==2.2.1
cmake==3.25.2
cmdstanpy==1.1.0
colorcet==3.0.1
colorlover==0.3.0
community==1.0.0b1
confection==0.0.4
cons==0.4.5
contextlib2==0.6.0.post1
contourpy==1.0.7
convertdate==2.4.0
cryptography==40.0.2
cufflinks==0.17.3
cvxopt==1.3.0
cvxpy==1.3.1
cycler==0.11.0
cymem==2.0.7
Cython==0.29.34
dask==2022.12.1
datascience==0.17.6
db-dtypes==1.1.1
dbus-python==1.2.16
debugpy==1.6.6
decorator==4.4.2
defusedxml==0.7.1
distributed==2022.12.1
dlib==19.24.1